title: Blog
author: Meredith Loughran
email: merej99@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meredith Loughran is front-end web designer who wants to learn coding. She blogs on Steemit and is very active on social media.

# social links
twitter_username: merej99 
github_username:  merej99
facebook_username: meredithj99

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
